// <auto-generated />
namespace IMS_2018_07_25.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class addcosttoitem : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addcosttoitem));
        
        string IMigrationMetadata.Id
        {
            get { return "201807282059210_add-cost-to-item"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
